### ISSUE TITLE
The used letters are not alphabeticle

### ISSUE THREAD

**Issue by TechSupport26** [kai-low256/Hangman#1]
Please order the letters used in alphabetical order.

**Comment by kai-low256** [comment]
It is in alphabetical order. 
what part are you talking about?

**Comment by TechSupport26** [comment]
![image](https://user-images.githubusercontent.com/65631811/160943477-f673f74f-9808-4d1b-94f5-302d67a1bccb.png)

**Comment by kai-low256** [comment]
Oh that.
It's in the order you used the letters.
I don't think It should be in alphabetical order. 
you can make it alphabetic if you want to.
